"""
pipeline.py
===========
Unified inference pipeline for the AI Behaviour Detection system.

Supports three inference paths:
  1. Master Fusion Model (preferred) — expects a wide fused feature DataFrame
     generated by MasterDataLoader, matching the schema stored in
     models/behavior_master_features.json.
  2. Deep CNN-BiLSTM Model (fallback) — expects raw sensor windows.
  3. Individual XGBoost sensor model (legacy fallback).

Missing sensors are handled gracefully: the pipeline fills absent feature
columns with NaN before passing them to XGBoost, which splits on missingness
natively.  A tolerance warning is emitted if >50% of master features are NaN.
"""

import json
import os
import warnings

import numpy as np
import pandas as pd

from app.ml.anomaly import AnomalousBehaviorDetector
from app.ml.classifiers import XGBoostClassifier, DeepBehaviorClassifier, MasterFusionClassifier
from app.ml.post_processing import PostProcessor
from app.ml.rule_engine import AlertEngine

# Path to the ordered feature list saved during training
_FEATURE_NAMES_PATH = os.path.join("models", "behavior_master_features.json")
_LABEL_ENCODER_PATH = os.path.join("models", "behavior_master_label_encoder.json")


def _load_json(path: str) -> dict | list | None:
    if os.path.exists(path):
        with open(path, "r") as f:
            return json.load(f)
    return None


class DetectionPipeline:
    """
    Unified pipeline to handle multiple models and post-processing.

    Args:
        use_master: If True (default), load and prefer the Master Fusion model.
                    Set to False to force fallback to individual sensor models.
    """

    def __init__(self, use_master: bool = True):
        self.anomaly_detector = AnomalousBehaviorDetector()
        self.xgb_classifier = XGBoostClassifier()
        self.deep_classifier = DeepBehaviorClassifier()
        self.post_processor = PostProcessor()
        self.alert_engine = AlertEngine()

        # Master model
        self.master_classifier: MasterFusionClassifier | None = (
            MasterFusionClassifier() if use_master else None
        )

        # Expected feature schema — populated lazily from disk
        self._master_feature_names: list[str] | None = _load_json(_FEATURE_NAMES_PATH)
        self._id_to_label: dict[int, str] | None = None

        raw_encoder = _load_json(_LABEL_ENCODER_PATH)
        if raw_encoder:
            # label_encoder is str→int; invert to int→str for prediction readout
            self._id_to_label = {int(v): k for k, v in raw_encoder.items()}

        # Default fallback mapping if encoder not saved yet
        if not self._id_to_label:
            self._id_to_label = {
                0: "Grazing",
                1: "Ruminating",
                2: "Resting",
                3: "Walking",
                4: "Other",
            }

    # ------------------------------------------------------------------
    #  Main inference entry point
    # ------------------------------------------------------------------

    def run_inference(
        self,
        device_id: str,
        raw_data: np.ndarray,
        features: pd.DataFrame,
    ) -> dict:
        """
        Runs the full detection pipeline for a single device snapshot.

        Args:
            device_id : Unique identifier for the cow / device.
            raw_data  : (channels, seq_len) NumPy array for the deep model.
            features  : DataFrame of statistical / fused features.
                        For the Master Model this should be the wide fused vector
                        produced by MasterDataLoader._align_single_session().
                        For individual sensor models, any feature DataFrame works.

        Returns:
            {
                "behavior"     : str  — predicted behavior label,
                "behavior_id"  : int  — integer class ID,
                "anomaly_score": float,
                "alerts"       : list[dict],
                "model_used"   : str  — which model path was taken,
                "uwb_available": bool — whether UWB features were non-NaN,
            }
        """
        # ---- 1. Anomaly Detection ----------------------------------------
        anomaly_scores = self.anomaly_detector.score_samples(features)
        smoothed_scores = self.post_processor.temporal_smoothing(anomaly_scores)

        # ---- 2. Classification -------------------------------------------
        model_used = "unknown"
        behavior_ids = None

        if (
            self.master_classifier is not None
            and self.master_classifier.model is not None
        ):
            try:
                aligned_features = self._align_to_master_schema(features, device_id)
                behavior_ids = self.master_classifier.predict(aligned_features)
                model_used = "master_fusion"
            except Exception as e:
                warnings.warn(
                    f"[DetectionPipeline] Master model inference failed for "
                    f"{device_id}: {e}. Falling back to deep model."
                )

        if behavior_ids is None:
            try:
                behavior_ids = self.deep_classifier.predict(raw_data)
                model_used = "deep_cnn_bilstm"
            except Exception as e:
                warnings.warn(
                    f"[DetectionPipeline] Deep model also failed: {e}. "
                    "Falling back to XGBoost individual sensor model."
                )
                behavior_ids = self.xgb_classifier.predict(features)
                model_used = "xgboost_individual"

        if behavior_ids is None or len(behavior_ids) == 0:
            raise RuntimeError(
                f"All inference paths failed for device '{device_id}'."
            )

        smoothed_behaviors = self.post_processor.majority_voting(behavior_ids.tolist())
        latest_behavior_id = int(smoothed_behaviors[-1])
        latest_behavior = self._id_to_label.get(latest_behavior_id, "Unknown")

        # ---- 3. UWB availability flag ------------------------------------
        uwb_available = False
        if self._master_feature_names:
            uwb_cols = [c for c in self._master_feature_names if c.startswith("uwb_")]
            if uwb_cols and not features.empty:
                present = [c for c in uwb_cols if c in features.columns]
                if present:
                    uwb_available = bool(features[present].notna().any().any())

        # ---- 4. Alert Generation -----------------------------------------
        alerts: list[dict] = []
        latest_score = float(smoothed_scores[-1]) if len(smoothed_scores) > 0 else 0.0

        alert = self.alert_engine.process_anomaly_score(device_id, latest_score)
        if alert:
            alerts.append(alert)

        behavior_alert = self.alert_engine.process_class_prediction(
            device_id, latest_behavior
        )
        if behavior_alert:
            alerts.append(behavior_alert)

        print(
            f"[{device_id}] Behavior: {latest_behavior} | "
            f"Anomaly: {latest_score:.3f} | Model: {model_used} | "
            f"UWB: {'OK' if uwb_available else 'MISSING (NaN fallback)'}"
        )

        return {
            "behavior": latest_behavior,
            "behavior_id": latest_behavior_id,
            "anomaly_score": latest_score,
            "alerts": alerts,
            "model_used": model_used,
            "uwb_available": uwb_available,
        }

    # ------------------------------------------------------------------
    #  Feature alignment helper
    # ------------------------------------------------------------------

    def _align_to_master_schema(
        self, features: pd.DataFrame, device_id: str
    ) -> pd.DataFrame:
        """
        Ensures *features* matches the exact column order that the Master Model
        was trained on.  Missing columns are filled with NaN (XGBoost handles
        them natively).  Extra columns are silently dropped.

        Emits a warning if more than 50% of expected features are absent.
        """
        if not self._master_feature_names:
            # No schema saved — pass features through as-is
            return features

        expected = self._master_feature_names
        aligned = pd.DataFrame(index=features.index)

        missing_count = 0
        for col in expected:
            if col in features.columns:
                aligned[col] = features[col]
            else:
                aligned[col] = np.nan
                missing_count += 1

        nan_ratio = missing_count / len(expected)
        if nan_ratio > 0.5:
            warnings.warn(
                f"[DetectionPipeline] {device_id}: {missing_count}/{len(expected)} "
                f"master features are missing ({nan_ratio:.0%}). "
                "Predictions may be unreliable."
            )

        return aligned
